# Enable true colors
set -g default-terminal "screen-256color"

# Change tmux prefix to <C-a>
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Split panes easily
unbind %
bind = split-window -h

unbind '"'
bind - split-window -v

# Quickly source tmux config
unbind r
bind r source-file ~/.tmux.conf

# Easy pane resizing
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# persist tmux sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Enable mouse mode
set -g mouse on

# Vim motions in copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# Vim tmux navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# tmux theme
set -g @plugin 'dracula/tmux'

# Initialize tmux plugins
run '~/.tmux/plugins/tpm/tpm'
