format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$time\
"""

add_newline = false
scan_timeout = 100
command_timeout = 1000

[directory]
format = "$path "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = "| $symbol ($branch)"

[git_status]
format = " $all_status$ahead_behind "

[nodejs]
symbol = ""
format = "| $symbol ($version) "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '| $time \$ '
