format = """
[](#471337)\
$username\
[](bg:#b13254 fg:#471337)\
$directory\
[](fg:#b13254 bg:#ff5349)\
$git_branch\
$git_status\
[](fg:#ff5349 bg:#ff7249)\
$nodejs\
$rust\
[](fg:#ff7249 bg:#ff9248)\
$time\
[ ](fg:#ff9248)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#471337"
style_root = "bg:#471337"
format = '[$user ]($style)'

[directory]
style = "bg:#b13254"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#ff5349"
format = '[[ $symbol $branch ](bg:#ff5349)]($style)'

[git_status]
style = "bg:#ff5349"
format = '[[($all_status$ahead_behind )](bg:#ff5349)]($style)'

[nodejs]
symbol = ""
style = "bg:#ff7249"
format = '[[ $symbol ($version) ](bg:#ff7249)]($style)'

[rust]
symbol = ""
style = "bg:#ff7249"
format = '[[ $symbol ($version) ](bg:#ff7249)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ff9248"
format = '[[ $time ](bg:#ff9248)]($style)'
